### ISSUE TITLE
Missing aarch64 artifact.

### ISSUE THREAD

**Issue by jimfcarroll** [cmake-maven-project/cmake-maven-project#53] opened 2023-04-06 17:33 UTC
Building with the deployed 3.25.2-b1 gives the following error on aarch64:

[ERROR] Failed to execute goal com.googlecode.cmake-maven-project:cmake-maven-plugin:3.25.2-b1:generate (cmake-generate) on project native-ai100-linux-aarch64: Unable to find/resolve artifact.: The following artifacts could not be resolved: com.googlecode.cmake-maven-project:cmake-binaries:jar:linux-arm_64:3.25.2-b1 (absent): com.googlecode.cmake-maven-project:cmake-binaries:jar:linux-arm_64:3.25.2-b1 was not found in https://nexus.kognition.ai/repository/public during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of nexus has elapsed or updates are forced -> [Help 1]

If I check it out and build either the current SNAPSHOT or release-3.25.2.b1 (skipping the integration tests, since they still fail for me) then it works, but if I rely on the deployed artifact, it fails with the above error.

**Comment by cowwoc** [comment] 2023-04-07 21:43
Duplicate of https://github.com/cmake-maven-project/cmake-maven-project/issues/52

**Closed by cowwoc** 2023-04-07 21:43 UTC

**Comment by jimfcarroll** [comment] 2023-04-08 13:02
Sorry about that. I should have checked first.
